export type Post = {
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  date: string; // ISO
  displayDate: string;
  category: string;
  excerpt: string;
  body: string[]; // paragraphs / list blocks as plain HTML-ish strings, rendered as-is
};

// Ported verbatim from the live WordPress site (gormanhardin.com) during the
// 2026-08-12 rebuild -- same URLs preserved so nothing needs a redirect.
export const posts: Post[] = [
  {
    slug: "diy-bookkeeping-mistakes",
    title: "Why “Do-It-Yourself” Bookkeeping Can Get Messy",
    metaTitle: "DIY Bookkeeping Mistakes to Avoid | Gorman Hardin",
    description:
      "Common DIY bookkeeping mistakes small businesses make and why they create tax surprises and lost opportunities for growth.",
    date: "2025-09-25",
    displayDate: "September 25, 2025",
    category: "Uncategorized",
    excerpt:
      "Many small business owners try to save money by doing the books themselves. Without the right training and tax planning, bookkeeping can quickly get out of control.",
    body: [
      "Many small business owners try to save money by doing the books themselves or having a spouse, family member, or trusted employee handle it. While it may seem like a simple solution, this often leads to DIY bookkeeping mistakes that create messy records, tax surprises, and lost opportunities for growth. Without the right training and planning around tax, bookkeeping can quickly get out of control.",
      "## Common Problems With DIY Bookkeeping",
      "One of the most costly errors is mixing personal and business accounts. This creates confusion, audit risk, and missed deductions.",
      "Another common problem is having no tax strategy. According to the IRS Small Business and Self-Employed Tax Center, poor bookkeeping is one of the most frequent issues they encounter, and it often leads to higher taxes or compliance headaches.",
      "Finally, many business owners miss growth opportunities. The U.S. Small Business Administration explains that strong financial management and accurate records are essential for monitoring cash flow and scaling a business.",
      "## Why Professional Bookkeeping Matters",
      "Professional bookkeeping prevents the common mistakes that cost you time and money. At Gorman Hardin, our approach goes beyond data entry — we build your books around your tax plan so you stay prepared year-round.",
      "We also provide full support for business owners who want more than bookkeeping. From payroll and tax planning to consulting, we've got you covered. Learn more on our [Full-Service Accounting](/full-service-accounting) page.",
      "## Take Control of Your Books",
      "Don't let DIY bookkeeping mistakes hold your business back. Professional bookkeeping gives you clarity, reduces tax headaches, and frees your time to focus on what matters most — running your business.",
      "Ready to move past messy books? [Schedule a discovery meeting](/contact) with our team today.",
    ],
  },
  {
    slug: "choosing-accounting-software-quickbooks-sage",
    title: "Choosing the Right Accounting Software for Your Business: QuickBooks, Sage, and More",
    metaTitle: "Accounting Software for your Business | Gorman Hardin CPA",
    description:
      "A comparison of QuickBooks, Sage, Xero, Wave, FreshBooks, Zoho Books, and NetSuite to help you choose the right accounting software.",
    date: "2024-12-20",
    displayDate: "December 20, 2024",
    category: "Business",
    excerpt:
      "Selecting the right accounting software can make a world of difference in your operations. Here's a look at QuickBooks, Sage, and a few alternatives.",
    body: [
      "In today's fast-paced business environment, selecting the right accounting software can make a world of difference in your operations. At Gorman Hardin CPA & Consulting, we understand how crucial this decision is for businesses of all sizes. Whether you're a startup, a growing enterprise, or an established firm, the right software can help streamline your financial processes, improve accuracy, and save valuable time.",
      "Let's explore some of the most popular accounting software options — QuickBooks, Sage, and a few alternatives — to help you make an informed choice.",
      "## QuickBooks: A Leader in Small Business Accounting",
      "QuickBooks by Intuit is often the go-to choice for small and medium-sized businesses. Its user-friendly interface and robust features make it a versatile option for various industries. Key features include easy integration with banking and payment platforms, automated invoicing, expense tracking, and payroll, cloud-based and desktop versions, and scalable solutions from QuickBooks Online to QuickBooks Enterprise.",
      "Best for: small to medium-sized businesses that need a comprehensive and easy-to-use accounting platform. QuickBooks also offers industry-specific versions tailored to contractors, nonprofits, and more.",
      "## Sage: A Trusted Name for Larger Businesses",
      "Sage is known for its powerful tools that cater to more complex accounting needs. While it's widely used by larger businesses, Sage also offers solutions for small businesses — advanced reporting and analytics, strong inventory management, multi-user and multi-currency options, and scalable tools like Sage 50 and Sage Intacct.",
      "Best for: businesses with more complex accounting needs or those requiring advanced inventory and financial analysis features.",
      "## Other Notable Accounting Software Options",
      "Xero — a cloud-based platform known for its clean interface and automation tools, ideal for small businesses and startups. Wave — a free option for small businesses with basic accounting needs. FreshBooks — great for freelancers and service-based businesses, focused on invoicing and time tracking. Zoho Books — part of the Zoho suite, affordable and feature-rich. NetSuite by Oracle — a comprehensive ERP solution for larger businesses.",
      "## How Gorman Hardin CPA & Consulting Can Help",
      "Choosing the right accounting software is not a one-size-fits-all decision. We take the time to understand your business's unique needs and recommend solutions tailored to your goals — software selection and implementation, training for your team, ongoing support and troubleshooting, and integration with your existing systems.",
      "Contact us today to discuss your needs and find the perfect solution for your business.",
    ],
  },
  {
    slug: "year-end-tax-preparation-checklist",
    title: "Year-End Tax Preparation Checklist: Maximize Deductions and Avoid Penalties",
    metaTitle: "Year-End Tax Preparation | Gorman Hardin CPA",
    description:
      "A 7-step checklist for year-end tax preparation covering records, deductions, 1099s, retirement contributions, and estimated taxes.",
    date: "2024-12-19",
    displayDate: "December 19, 2024",
    category: "Business, Consulting",
    excerpt:
      "As the end of the year approaches, it's crucial to get your tax affairs in order. Follow this checklist to make year-end tax prep seamless.",
    body: [
      "As the end of the year approaches, it's crucial to get your tax affairs in order. With proper planning, you can save money, reduce stress, and ensure compliance with tax regulations. To help you get started, follow this comprehensive checklist to make your year-end tax preparation seamless and efficient.",
      "## 1. Gather All Financial Records",
      "Organize your income statements, expense receipts, and bank records so everything is in one place, making it easier to calculate deductions and ensure accuracy.",
      "## 2. Review Your Expenses for Deductions",
      "Identify deductible expenses like business travel, office supplies, or charitable contributions. Consider potential end-of-year opportunities, such as prepaying certain expenses to maximize deductions.",
      "## 3. Prepare and Issue 1099s",
      "If applicable, ensure you prepare and issue 1099 forms for contractors you've paid $600 or more. Gather W-9 forms and payment details now to avoid last-minute issues.",
      "## 4. Contribute to Retirement Accounts",
      "Make contributions to your IRA, 401(k), or other retirement plans for valuable tax benefits and future savings.",
      "## 5. Plan for Estimated Taxes",
      "If you're self-employed or own a small business, ensure your estimated tax payments are on track — missing payments can result in penalties.",
      "## 6. Review Tax Law Changes",
      "Review any new tax laws that could affect your filing, and consult a CPA if you're unsure how changes impact your deductions or credits.",
      "## 7. Work with a CPA for Expert Advice",
      "A CPA can help you navigate complex tax rules, identify opportunities for savings, and ensure compliance. Contact us today to learn how we can make your tax season stress-free.",
    ],
  },
  {
    slug: "starting-a-business-in-kentucky-a-step-by-step-guide",
    title: "Starting a Business in Kentucky: A Step-by-Step Guide",
    metaTitle: "Starting a Business in Kentucky | Gorman Hardin CPA",
    description:
      "A 14-step guide to starting a business in Kentucky — entity selection, registration, licenses, tax IDs, insurance, and bookkeeping.",
    date: "2024-11-21",
    displayDate: "November 21, 2024",
    category: "Business, Consulting",
    excerpt:
      "Starting a business in Kentucky is exciting but can feel overwhelming without the right guidance. Here's a step-by-step guide to get your business off the ground.",
    body: [
      "Starting a business in Kentucky is an exciting journey, but it can also feel overwhelming without the right guidance. At Gorman Hardin CPA and Consulting, we've helped countless entrepreneurs successfully navigate the process of launching their businesses.",
      "## Step 1: Choose the Right Business Structure",
      "Common options include Sole Proprietorship, Partnership, LLC, and Corporation. For most small businesses, an LLC provides the best balance of protection and simplicity.",
      "## Step 2: Register Your Business Name",
      "Register your business name with the Kentucky Secretary of State through the Kentucky Business One-Stop Portal.",
      "## Step 3: Obtain Licenses and Permits",
      "Depending on your industry, you may need specific licenses or permits — check the Kentucky Business One-Stop Portal for exact requirements.",
      "## Step 4: Get Your Tax IDs",
      "Apply for a Federal EIN from the IRS and complete a Tax Registration Application through the Kentucky Department of Revenue.",
      "## Step 5: Register for Sales Tax",
      "If your business sells products, register for a sales tax account with the Kentucky Department of Revenue.",
      "## Step 6: Secure Insurance",
      "Depending on your operations, you may need general liability, workers' compensation, and business property insurance.",
      "## Step 7: Develop a Business Plan",
      "A strong business plan outlines your goals, financial projections, marketing strategies, and operational processes.",
      "## Step 8: Secure Financing",
      "If you need funding, consider applying for a business loan through a bank, credit union, or the SBA.",
      "## Step 9: Choose a Business Location",
      "Select a location convenient for both your customers and employees.",
      "## Step 10: Hire Employees (If Needed)",
      "Comply with federal and state labor laws — the Kentucky Labor Cabinet provides resources to help.",
      "## Step 11: Set Up Bookkeeping",
      "Keeping accurate financial records is critical. We can help you establish a streamlined system tailored to your needs.",
      "## Step 12: Create a Website",
      "A professional website is essential — it's the online face of your business.",
      "## Step 13: Build a Marketing Plan",
      "Include both online methods (social media, SEO) and offline strategies (community sponsorships, print advertising).",
      "## Step 14: Open a Business Bank Account",
      "Keep your personal and business finances separate to simplify bookkeeping and ensure tax compliance.",
      "Starting a business in Kentucky is a big step, and we're here to help you every step of the way. Contact us today — we'd love to help you bring your vision to life!",
    ],
  },
  {
    slug: "tax-planning-and-bookkeeping-services",
    title: "Why You Should Use a CPA for Bookkeeping",
    metaTitle: "Tax planning & bookkeeping Services | Gorman Hardin CPA",
    description:
      "Nine reasons working with a CPA for bookkeeping — accuracy, time savings, better tax prep, cash flow management, and audit protection.",
    date: "2024-11-12",
    displayDate: "November 12, 2024",
    category: "Business, Consulting",
    excerpt:
      "Bookkeeping can be one of the most challenging aspects of running a small business. Here's why working with a CPA is one of the best decisions you can make.",
    body: [
      "As a small business owner, tax planning and bookkeeping can be one of the most challenging aspects of running your business. While you're busy handling daily operations, bookkeeping can easily get overlooked. Here's why working with a CPA for bookkeeping is one of the best decisions you can make for your business.",
      "## 1. Accurate Financial Records",
      "A CPA is trained to handle bookkeeping tasks meticulously, ensuring every transaction is recorded correctly.",
      "## 2. Time and Cost Efficiency",
      "A CPA frees up your time to focus on growing your business, and is often more cost-effective than an in-house bookkeeper.",
      "## 3. Better Tax Preparation",
      "Accurate bookkeeping is the foundation for good tax preparation, making it easier to identify deductions and credits.",
      "## 4. Cash Flow Management",
      "Proper bookkeeping helps you track cash flow and make smarter decisions, avoiding shortfalls.",
      "## 5. Financial Reporting and Insights",
      "A CPA provides detailed financial reports — profit and loss, balance sheets, cash flow statements — essential for strategic planning.",
      "## 6. Compliance and Regulations",
      "A CPA ensures your books comply with federal, state, and local laws, reducing the risk of errors and penalties.",
      "## 7. Scalable Solutions",
      "As your business grows, a CPA can adjust your bookkeeping processes to meet increasing demands.",
      "## 8. Audit Protection",
      "Accurate bookkeeping by a CPA ensures your records are organized in case of an audit.",
      "## 9. Peace of Mind",
      "Trust that your financial records are accurate, organized, and compliant, so you can focus on running your business.",
      "Bookkeeping is essential to running a successful business, and partnering with a CPA makes the process more efficient, accurate, and cost-effective. Contact Gorman Hardin CPA and Consulting today.",
    ],
  },
  {
    slug: "tax-saving-tips-from-a-cpa",
    title: "Tax Saving Tips from a CPA",
    metaTitle: "Tax Saving Tips | Maximize Your Savings | Gorman Hardin CPA",
    description:
      "Nine tax-saving strategies for small business owners — deductions, retirement contributions, Section 179, mileage tracking, and tax credits.",
    date: "2024-11-12",
    displayDate: "November 12, 2024",
    category: "Business, Consulting",
    excerpt:
      "Navigating the complex world of taxes can be overwhelming. Here are key tax-saving tips from a CPA to help you optimize your tax situation.",
    body: [
      "As a small business owner, navigating the complex world of taxes can be overwhelming. With the right strategies in place, you can minimize your tax liability and keep more of your hard-earned money. Here are key tax-saving tips from a CPA.",
      "## 1. Take Advantage of Business Deductions",
      "Common deductions include home office, vehicle expenses, supplies and equipment, employee wages, and marketing expenses.",
      "## 2. Contribute to Retirement Plans",
      "Contributions to a 401(k) or SEP IRA are tax-deductible and lower your taxable income while saving for the future.",
      "## 3. Utilize the Section 179 Deduction",
      "Deduct the full cost of qualifying equipment, machinery, or software in the year you purchase it rather than depreciating it over several years.",
      "## 4. Keep Track of Your Mileage",
      "The IRS allows a standard mileage rate deduction for business driving — keeping a log can add up to significant savings. (Rate changes annually — confirm the current-year figure before filing.)",
      "## 5. Hire Family Members",
      "Hiring a spouse or children can provide additional tax benefits, especially if they fall under a lower tax bracket.",
      "## 6. Defer Income",
      "Deferring income near year-end can reduce your current-year taxable income, especially if you expect a lower bracket next year.",
      "## 7. Take Advantage of Tax Credits",
      "Credits like the R&D Tax Credit, Work Opportunity Tax Credit, and energy-efficient equipment credits can significantly reduce your tax bill.",
      "## 8. Keep Your Records Organized",
      "Organized records make it easier to identify deductible expenses and reduce the risk of costly errors.",
      "## 9. Consult a CPA Regularly",
      "A CPA can provide personalized advice and ensure you're taking advantage of every available deduction and credit throughout the year.",
      "Tax savings don't happen by chance — they require proactive planning and the right strategies. Reach out to Gorman Hardin CPA and Consulting today.",
    ],
  },
];
